### ISSUE TITLE
Mapping more functionality for knob controls

### ISSUE THREAD

**Issue by mperezInnotas** [chrisspiegl/Behringer-X-Touch-Presets#2]
I was going thru your video and I was wondering if there is a way to have a button affect the knobs such that they effectively output another midi code. For example, in Layer B button 5, I'd like for it to be pressed and stay on (I think this is the toggle option in the xtouch editor?) and when that is turned on have Knob 1 change the red saturation value.  When I looked at the Midi2LR options I see an option to show the HSL/Color panel, and was hoping there was some way to have a button toggle effectively allow another command to be mapped to the knob control.   I've seen something like this with PFixer and LRControl so I suspect it's a editor change I need to apply to the hardware first but I'm new to the editor.   

Thanks for any assistance. -Miro

**Comment by chrisspiegl** [comment]
Hi Miro,
First: I do no longer use the Behriner X-Touch Interface.
Second: I also never used it in this way. I only programmed my own solutions to interact and send Midi Signals to the device / receive them from the device. So I only wanted clean and predictable midi key-codes (which is what I built with this package).
Hope you can find some solution.
